version: "3"

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "hideout"

  mongodb:
    image: mongo:7.0.12
    ports:
      - "27017:27017"