hideout:
  url: "http://localhost:8080"
  database:
    url: "jdbc:h2:./test;MODE=POSTGRESQL"
    driver: "org.h2.Driver"
    user: ""
    password: ""
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:./test;MODE=POSTGRESQL"
    username: ""
    password: ""
