insert into posts (id, actor_id, instance_id, overview, content, text, created_at, visibility, url, repost_id, reply_id, sensitive, ap_id, deleted, hide, move_to)
VALUES (1, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/1',
        null, null, false, 'https://example.com/users/1/posts/1', false,false,null),
       (2, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/2',
        null, 1, false, 'https://example.com/users/1/posts/2', false,false,null),
       (3, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/3',
        null, null, false, 'https://example.com/users/1/posts/3', false,false,null),
       (4, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/4',
        null, 3, false, 'https://example.com/users/1/posts/4', false,false,null),
       (5, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/5',
        null, null, false, 'https://example.com/users/1/posts/5', false,false,null),
       (6, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/6',
        null, null, false, 'https://example.com/users/1/posts/6', false,false,null),
       (7, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/7',
        null, null, false, 'https://example.com/users/1/posts/7', false,false,null),
       (8, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/8',
        null, 7, false, 'https://example.com/users/1/posts/8', false,false,null),
       (9, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/9',
        null, null, false, 'https://example.com/users/1/posts/9', false,false,null),
       (10, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/10',
        null, 9, false, 'https://example.com/users/1/posts/10', false,false,null),
       (11, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/11',
        null, null, false, 'https://example.com/users/1/posts/11', false,false,null),
       (12, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/12',
        null, null, false, 'https://example.com/users/1/posts/12', false,false,null),
       (13, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/13',
        null, null, false, 'https://example.com/users/1/posts/13', false,false,null),
       (14, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/14',
        null, 13, false, 'https://example.com/users/1/posts/14', false,false,null),
       (15, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/15',
        null, null, false, 'https://example.com/users/1/posts/15', false,false,null),
       (16, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/16',
        null, 15, false, 'https://example.com/users/1/posts/16', false,false,null),
       (17, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/17',
        null, null, false, 'https://example.com/users/1/posts/17', false,false,null),
       (18, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/18',
        null, null, false, 'https://example.com/users/1/posts/18', false,false,null),
       (19, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/19',
        null, null, false, 'https://example.com/users/1/posts/19', false,false,null),
       (20, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/20',
        null, 19, false, 'https://example.com/users/1/posts/20', false,false,null),
       (21, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/21',
        null, null, false, 'https://example.com/users/1/posts/21', false,false,null),
       (22, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/22',
        null, 21, false, 'https://example.com/users/1/posts/22', false,false,null),
       (23, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/23',
        null, null, false, 'https://example.com/users/1/posts/23', false,false,null),
       (24, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/24',
        null, null, false, 'https://example.com/users/1/posts/24', false,false,null),
       (25, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/25',
        null, null, false, 'https://example.com/users/1/posts/25', false,false,null),
       (26, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/26',
        null, 25, false, 'https://example.com/users/1/posts/26', false,false,null),
       (27, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/27',
        null, null, false, 'https://example.com/users/1/posts/27', false,false,null),
       (28, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/28',
        null, 27, false, 'https://example.com/users/1/posts/28', false,false,null),
       (29, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/29',
        null, null, false, 'https://example.com/users/1/posts/29', false,false,null),
       (30, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/30',
        null, null, false, 'https://example.com/users/1/posts/30', false,false,null),
       (31, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/31',
        null, null, false, 'https://example.com/users/1/posts/31', false,false,null),
       (32, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/32',
        null, 31, false, 'https://example.com/users/1/posts/32', false,false,null),
       (33, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/33',
        null, null, false, 'https://example.com/users/1/posts/33', false,false,null),
       (34, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/34',
        null, 33, false, 'https://example.com/users/1/posts/34', false,false,null),
       (35, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/35',
        null, null, false, 'https://example.com/users/1/posts/35', false,false,null),
       (36, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/36',
        null, null, false, 'https://example.com/users/1/posts/36', false,false,null),
       (37, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/37',
        null, null, false, 'https://example.com/users/1/posts/37', false,false,null),
       (38, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/38',
        null, 37, false, 'https://example.com/users/1/posts/38', false,false,null),
       (39, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/39',
        null, null, false, 'https://example.com/users/1/posts/39', false,false,null),
       (40, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/40',
        null, 39, false, 'https://example.com/users/1/posts/40', false,false,null),
       (41, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/41',
        null, null, false, 'https://example.com/users/1/posts/41', false,false,null),
       (42, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/42',
        null, null, false, 'https://example.com/users/1/posts/42', false,false,null),
       (43, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/43',
        null, null, false, 'https://example.com/users/1/posts/43', false,false,null),
       (44, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/44',
        null, 43, false, 'https://example.com/users/1/posts/44', false,false,null),
       (45, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/45',
        null, null, false, 'https://example.com/users/1/posts/45', false,false,null),
       (46, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/46',
        null, 45, false, 'https://example.com/users/1/posts/46', false,false,null),
       (47, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/47',
        null, null, false, 'https://example.com/users/1/posts/47', false,false,null),
       (48, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/48',
        null, null, false, 'https://example.com/users/1/posts/48', false,false,null),
       (49, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/49',
        null, null, false, 'https://example.com/users/1/posts/49', false,false,null),
       (50, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/50',
        null, 49, false, 'https://example.com/users/1/posts/50', false,false,null),
       (51, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/51',
        null, null, false, 'https://example.com/users/1/posts/51', false,false,null),
       (52, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/52',
        null, 51, false, 'https://example.com/users/1/posts/52', false,false,null),
       (53, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/53',
        null, null, false, 'https://example.com/users/1/posts/53', false,false,null),
       (54, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/54',
        null, null, false, 'https://example.com/users/1/posts/54', false,false,null),
       (55, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/55',
        null, null, false, 'https://example.com/users/1/posts/55', false,false,null),
       (56, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/56',
        null, 55, false, 'https://example.com/users/1/posts/56', false,false,null),
       (57, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/57',
        null, null, false, 'https://example.com/users/1/posts/57', false,false,null),
       (58, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/58',
        null, 57, false, 'https://example.com/users/1/posts/58', false,false,null),
       (59, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/59',
        null, null, false, 'https://example.com/users/1/posts/59', false,false,null),
       (60, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/60',
        null, null, false, 'https://example.com/users/1/posts/60', false,false,null),
       (61, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/61',
        null, null, false, 'https://example.com/users/1/posts/61', false,false,null),
       (62, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/62',
        null, 61, false, 'https://example.com/users/1/posts/62', false,false,null),
       (63, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/63',
        null, null, false, 'https://example.com/users/1/posts/63', false,false,null),
       (64, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/64',
        null, 63, false, 'https://example.com/users/1/posts/64', false,false,null),
       (65, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/65',
        null, null, false, 'https://example.com/users/1/posts/65', false,false,null),
       (66, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/66',
        null, null, false, 'https://example.com/users/1/posts/66', false,false,null),
       (67, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/67',
        null, null, false, 'https://example.com/users/1/posts/67', false,false,null),
       (68, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/68',
        null, 67, false, 'https://example.com/users/1/posts/68', false,false,null),
       (69, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/69',
        null, null, false, 'https://example.com/users/1/posts/69', false,false,null),
       (70, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/70',
        null, 69, false, 'https://example.com/users/1/posts/70', false,false,null),
       (71, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/71',
        null, null, false, 'https://example.com/users/1/posts/71', false,false,null),
       (72, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/72',
        null, null, false, 'https://example.com/users/1/posts/72', false,false,null),
       (73, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/73',
        null, null, false, 'https://example.com/users/1/posts/73', false,false,null),
       (74, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/74',
        null, 73, false, 'https://example.com/users/1/posts/74', false,false,null),
       (75, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/75',
        null, null, false, 'https://example.com/users/1/posts/75', false,false,null),
       (76, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/76',
        null, 75, false, 'https://example.com/users/1/posts/76', false,false,null),
       (77, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/77',
        null, null, false, 'https://example.com/users/1/posts/77', false,false,null),
       (78, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/78',
        null, null, false, 'https://example.com/users/1/posts/78', false,false,null),
       (79, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/79',
        null, null, false, 'https://example.com/users/1/posts/79', false,false,null),
       (80, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/80',
        null, 79, false, 'https://example.com/users/1/posts/80', false,false,null),
       (81, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/81',
        null, null, false, 'https://example.com/users/1/posts/81', false,false,null),
       (82, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/82',
        null, 81, false, 'https://example.com/users/1/posts/82', false,false,null),
       (83, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/83',
        null, null, false, 'https://example.com/users/1/posts/83', false,false,null),
       (84, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/84',
        null, null, false, 'https://example.com/users/1/posts/84', false,false,null),
       (85, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/85',
        null, null, false, 'https://example.com/users/1/posts/85', false,false,null),
       (86, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/86',
        null, 85, false, 'https://example.com/users/1/posts/86', false,false,null),
       (87, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/87',
        null, null, false, 'https://example.com/users/1/posts/87', false,false,null),
       (88, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/88',
        null, 87, false, 'https://example.com/users/1/posts/88', false,false,null),
       (89, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/89',
        null, null, false, 'https://example.com/users/1/posts/89', false,false,null),
       (90, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/90',
        null, null, false, 'https://example.com/users/1/posts/90', false,false,null),
       (91, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/91',
        null, null, false, 'https://example.com/users/1/posts/91', false,false,null),
       (92, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/92',
        null, 91, false, 'https://example.com/users/1/posts/92', false,false,null),
       (93, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/93',
        null, null, false, 'https://example.com/users/1/posts/93', false,false,null),
       (94, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/94',
        null, 93, false, 'https://example.com/users/1/posts/94', false,false,null),
       (95, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/95',
        null, null, false, 'https://example.com/users/1/posts/95', false,false,null),
       (96, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/96',
        null, null, false, 'https://example.com/users/1/posts/96', false,false,null),
       (97, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/97',
        null, null, false, 'https://example.com/users/1/posts/97', false,false,null),
       (98, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/98',
        null, 97, false, 'https://example.com/users/1/posts/98', false,false,null),
       (99, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'FOLLOWERS', 'https://example.com/users/1/posts/99',
        null, null, false, 'https://example.com/users/1/posts/99', false,false,null),
       (100, 1,1,null, '<p>this is test</p>', 'this is test', current_timestamp, 'PUBLIC', 'https://example.com/users/1/posts/100',
        null, 99, false, 'https://example.com/users/1/posts/100', false,false,null);